services:
  - type: web
    name: laravel-app
    env: docker
    buildCommand: docker-compose build app
    startCommand: docker-compose up app
    dockerfilePath: Dockerfile
    port: 8080

  - type: web
    name: nginx
    env: docker
    buildCommand: docker-compose build nginx
    startCommand: docker-compose up nginx
    dockerfilePath: Dockerfile
    port: 80